config/routes.rb
Rails.application.routes.draw do
  resources :comments
    
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "astro#home"
    get 'index2.html', to: 'astro#index2'
    get 'index.html', to: 'astro#home'
    
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astro.rb
class Astro< ActiveRecord::Base
   
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
     validates :title, presence: true, length: {minimum: 3, maximum: 50}
   validates :body, presence: true, length: {minimum: 10, maximum: 5000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/astro_controller.rb
class AstroController<ApplicationController
   def home       
   end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base

     

  # GET /comments/1
  # GET /comments/1.json
  def show
     
  end

  # GET /comments/new
  def new
    @comment = Comment.new
     
  end

  # GET /comments/1/edit
  def edit
  end

  # Comment /comments
  # Comment /comments.json
  def create
    @comment = Comment.new(comment_params)
      
    
      if @comment.save
        flash[:success]="succesfully Submited"
        redirect_to posts_path
        
      else
        render :new 
        
      end
    
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
   
      if @comment.update(comment_params)
        flash[:success]="succesfully Submited"
        redirect_to posts_path
        
      else
       render :edit
         end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_Comment
      @comment = Comment.find(params[:id])
    end

  private

    def comment_params
      params.require(:comment).permit(:title, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
      @comment = Comment.new
      @comments = Comment.all
  end

  # GET /posts/new
  def new
    @post = Post.new
     
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
   private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/astro/_footer.html.erb
  <footer>
        <div class="container">

            <div class="row text-center">
                <ul class="list-inline">

                    <li>
                        <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-dropbox fa-2x"></i></a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-flickr fa-2x"></i></a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-github fa-2x"></i></a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-linkedin fa-2x"></i></a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-tumblr fa-2x"></i></a>
                    </li>


                </ul>
            </div>

            <div class="row text-center">
                <ul class="menu list-inline">

                    <li>
                        <a href="#">Home</a>
                    </li>

                    <li>
                        <a href="#">About</a>
                    </li>

                    <li>
                        <a href="#">Blog</a>
                    </li>

                    <li>
                        <a href="#">Gallery</a>
                    </li>

                    <li>
                        <a href="#">Contact</a>
                    </li>

                </ul>
            </div>


        </div>
        <div class="row text-center" style="width:100%;">
            <p class="m-0 text-center text-white">Doveloped By:<a href="http://www.darhiwala.in">Anurag@darhiwala.in</a><br>Copyright &copy; website 2017</p>
        </div>
    </footer>

app/views/astro/_navbar.html.erb
<%= stylesheet_link_tag    "main", media: "all", "data-turbolinks-track" => true %>
<header class="navbar1 container-fluid">
        <div class="row">
            <div class="col-md-2 navbar-brand">PanditJiAstro</div>
            <div class="col-md-10">

                <ul class="scroll_nav nav navbar-nav ">
                    <li class="active"><a href="index.html">Home<span class="sr-only">(current)</span></a></li>
                     <li><%=link_to "BLOG",posts_path,class: "" ,id: "" %></li>
                     <li><a href="index2.html">Hindi Astro</a></li>
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle">Tools<span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li><a href="#ask">Ask To Parrot</a></li>

                            <li><a href="#a_forcaster">Ascendant Forcaster</a></li>

                        </ul>

                    </li>
                    <li><a href="indexp.html">Product</a></li>
                    <li class="active"><a>Contact : +91-981192292</a></li>

                </ul>
            </div>

        </div>



    </header>


    <nav class="navbar navbar-default navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
      </button>
                <a class="navbar-brand"></a>
            </div>



            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="index.html">Home<span class="sr-only">(current)</span></a></li>
                    <li><%=link_to "BLOG",posts_path,class: "" ,id: "" %></li>
                    <li><a href="index2.html">Hindi Astro</a></li>
                    

                    <li class="dropdown">
                        <a class="dropdown-toggle">Tools<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#ask">Ask To Parrot</a></li>

                            <li><a href="#a_forcaster">Ascendant Forcaster</a></li>


                        </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a>Contact : +91-981192292</a></li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/comments/_form.html.erb
<%=render 'shared/error',obj: @comment %>

    <div class="row">
        <div class="col-md-12 col-sm-offset-1">

            <%= form_with(model: comment, local: true) do |form| %>


                <div class="form-group field">
                    <%#= form.label :Name,class: "col-sm-2 control-label" %>
                        <div class="col-sm-10">
                            <%= form.text_field :title, id: :comment_title ,class: "form-control",placeholder: "Name" %>
                        </div>
                </div>
                        <div class="form-group field">
                            <%#= form.label :body,class: "col-sm-2 control-label" %>
                                <div class="col-sm-10">
                                    <%= form.text_area :body, id: :comment_body,class: "form-control",placeholder: "Body" %>
                                </div>
                        </div>

                        <div class="form-group actions">
                            <div class="col-sm-10">
                                <%= form.submit class: "btn btn-success" %>

                            </div>
                        </div>
                       
                        <% end %>

                
        </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<%= stylesheet_link_tag 'custom', media: 'all' %>
<%= render 'astro/navbar' %>
<p id="notice"><%= notice %></p>


<h1>Comments</h1>

    
<% @comments.each do |comment| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <h4><%=link_to comment.title,comment  %></h4>
            </div>
            <div class="article-body">
              <%=truncate(comment.body,length: 300)  %>
            </div>
        </div>
    </div>
</div>
  <% end %>
 
<br>
<%= render 'astro/footer' %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AstroWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%=render 'shared/error',obj: @post %>
    <div class="row">
        <div class="col-md-12">
            <%= form_with(model: post, local: true) do |form| %>

                <div class="form-group">
                    <%= form.label :title,class: "col-sm-2 control-label" %>
                        <div class="col-sm-10">
                            <%= form.text_field :title, id: :post_title ,class: "form-control",placeholder: "Title" %>
                        </div>
                </div>


                <div class="form-group field">
                    <%= form.label :body,class: "col-sm-2 control-label" %>
                        <div class="col-sm-10">
                            <%= form.text_area :body, id: :post_body, :cols => "10", :rows => "10",class: "form-control",placeholder: "Body" %>
                        </div>
                </div>

                <div class="form-group actions">
                    <div class="col-sm-offset-2 col-sm-10">
                        <%= form.submit class: "btn btn-default" %>
                            
                    </div>
                </div>
                    </div>
                        </div>
            <% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'astro/navbar' %>
<%= stylesheet_link_tag 'custom', media: 'all' %>
<%= render 'shared/flash_messages' %> 
<div class="row">
<h1 class="col-xs-10 col-xs-offset-1">Our Posts</h1>
<%#= link_to "New Article",new_article_path,class: "btn btn-success col-xs-2" %>
</div>
<% @posts.each do |post| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-1">
        <div class="well well-lg">
            <div class="article-title">
                <h2><%=link_to post.title,post  %></h2>
            </div>
            <div class="article-body">
              <%=truncate(post.body,length: 300)  %>
            </div>

      <%#= link_to "Edit",edit_article_path(a), class: "btn btn-primary btn-xs" %>
     <%#= link_to "Delete This Article",article_path(a),method: :delete,data: {confirm: "Are You Sure To Delete This Article ?"},class: "btn btn-danger btn-xs"  %>
        </div>
    </div>
</div>
  <% end %>
<%= render 'astro/footer' %>
    

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'astro/navbar' %>
<%= stylesheet_link_tag 'custom', media: 'all' %>
<%= render 'shared/flash_messages' %> 


<div class="row">
<%= link_to "Back To All Articles",posts_path(@post),  class: "btn btn-success col-xs-2 col-xs-offset-1" %>
</div>
<br>
<div class="container-fluid">
  <div class="row">
    
    <div class="well col-xs-8 col-xs-offset-1">
        <h2 style="col-xs-6 col-xs-offset-1"><%= @post.title %></h2>
        <hr>
        <p><%=simple_format(@post.body)  %></p>

        <hr>
         <div class="article_actions">
             
         </div>
    </div>
  </div>
    
    
</div>

<div class="container-fluid">
  <div class="row">
    <h1 style="margin-left:30px;">Comment</h1>
    <div class="col-xs-8 col-xs-offset-1">
      <%= render 'comments/form', comment: @comment %>
        <%= render 'shared/comments', comment: @comments %>
    </div>
  </div>
</div>


<%= render 'astro/footer' %>

app/views/shared/_comments.html.erb
<p id="notice"><%= notice %></p>    
<% comment.each do |comment| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <h2><%=link_to comment.title,comment  %></h2>
            </div>
            <div class="article-body">
              <%=truncate(comment.body,length: 300)  %>
            </div>

      <%#= link_to "Edit",edit_article_path(a), class: "btn btn-primary btn-xs" %>
     <%#= link_to "Delete This Article",article_path(a),method: :delete,data: {confirm: "Are You Sure To Delete This Article ?"},class: "btn btn-danger btn-xs"  %>
        </div>
    </div>
</div>
  <% end %>
 
<br>


app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%=pluralize(obj.errors.count,"error") %>
                     Prohibited from submiting
                </h2>
             <div class="panel-body">
                <% obj.errors.full_messages.each do |msg| %>
                  <ul><li><%= msg %></li></ul>
                <% end %>
             </div>
            </div>
        </div>
    </div>
</div>
    
<% end %>

app/views/shared/_flash_messages.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-1">
        <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div,msg,:id =>"flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
</div>